### ISSUE TITLE
Fabric Port

### ISSUE THREAD

**Issue by MinimumADHD** [zehmaria/createlowheated#1]
Hey, is there in planning any sort of port for the mod via the [Architectury](https://www.curseforge.com/minecraft/mc-mods/architectury-api) API?

**Comment by zehmaria** [comment]
Sorry, there is no planning of any sort for a Fabric Port right now. I never used Architectury or coded for Fabric, and even coding for Forge is something new to me, those few small mods were my firsts, so doing the same thing for both mod-loaders was never on my radar. I mostly wrote those for personal use and for a modpack I'm working on anyway. So, extending that work to cover a whole extra thing would be a lot of work and management headaches/maintenance that I would rather avoid, as I don't want to overwhelm myself. 

I won't say never, as things tend to change and supporting both loaders would be cool, but right now that would be a no.

**Comment by MinimumADHD** [comment]
Alright, it's cool, good learning then.
