### ISSUE TITLE
kubejs compatibility

### ISSUE THREAD

**Issue by gruniu8** [zehmaria/createlowheated#2]
hello! i wanted to use this mod in my modpack and i can't add new recipes using kubejs with .lowheated()
could you fix that?

**Comment by zehmaria** [comment]
Unfortunately, I found no easy fix. I looked into it, and while the feature [.heated(), .superheated()] from "Kubejs Create" seems trivial, adding .lowheated() from here into the existing addon of Kubejs doesn't seem like so. The only way seems to be to implement a full compat from the ground up, here or in a separated mod. However, that would be quite the pain for such singular thing. So, I don't know if I will ever come to do it, as I would need to learn how to do a whole Kubejs addon.  

So, don't hold your breath waiting. But, meanwhile, you can still use event.custom from Kubejs to code a small function for you to reuse, and that would achieve the same result. That's if you feel like the extra few lines are worth the effort. I use kubejs, and that's what I've always done.

**Comment by danbrown** [comment]
@gruniu8 @zehmaria I don't think a direct compatibility is needed. You can create new recipes using "lowheated" using the `data` folder inside kubejs, it will work exactly like a datapack.

For example, create in this path folder: `.minecraft/kubejs/data/DATAPACKNAME/recipes/new_recipe.json`

```json
{
    "type": "create:mixing",
    "heatRequirement": "lowheated",
    
    "ingredients": [
      {
        "item": "minecraft:stick"
      },
      {
        "tag": "createaddition:plants"
      },
      {
        "tag": "createaddition:plants"
      },
      {
        "fluidTag": "forge:plantoil",
        "amount": 150
      }
    ],
    "results": [
      {
        "item": "createaddition:biomass"
      }
    ]
  }
  ```

With this you don't need to close and reopen Minecraft to test new recipes, just use the `/reload` command.
Hope this helps!

**Comment by zehmaria** [comment]
at long last, this has been added.
