### ISSUE TITLE
Low-heated recipes don't work if Destroy is installed

### ISSUE THREAD

**Issue by ElRichiRicon** [zehmaria/createlowheated#5]
In NeoForge 47.1.104 - 1.20.1
Mod list:
Create 0.5.1f
Create Low-Heated 1.20.1-0.5.1f-g
Destroy 0.8
JEI 15.3.0.4

Recipes that indicate `"heatRequirement" : "lowheated"` require an active Blaze Burner instead, if Destroy is installed.

![image](https://github.com/zehmaria/createlowheated/assets/45831667/6d7dda85-cc96-480d-bbd1-820785ad6bc6)

It is not just a JEI issue, I've attempted the recipe, and it doesn't work.

**Comment by zehmaria** [comment]
Okay, I got the recipe working here. Some time ago, I had already changed something predicting that this might happen, but my changes missed two occurrences. So despite the hindsight, it was still broken anyway. Well, I didn't know of any mod that added another heat condition at the time, so I ended up not testing it fully, tho. 

Well, I still need to fix the visual thingy, to indicate the block right. So, the upload will happen a bit later.
